### ISSUE TITLE
[Review] As a user, I can tag a question as easy, medium or hard 

### ISSUE THREAD

**Issue by rockman007372** [AY2223S2-CS2103T-W11-3/tp#106]
... so that I can review questions of the same difficulty level.

**Comment by ruiyigan** [comment]
@rockman007372 @unfazing to clarify, can the user tag questions other than these three tags?

**Comment by rockman007372** [comment]
> tag questions other than these three tags?

Currently yes. I am leaning towards letting them tag whatever they want to reduce amount of codes to write + debug.

**Comment by ruiyigan** [comment]
Ohh ok got it!
