### ISSUE TITLE
[Main] Change prefix to reduce ambiguity in commands

### ISSUE THREAD

**Issue by unfazing** [AY2223S2-CS2103T-W11-3/tp#115]
For example, if a user were to type in "add q/what is a/b testing? a/a/b testing is…" the expected card created should have:
question - "what is a/b testing?"
answer - "a/b testing is..."

it is ambiguous which token "a/" should be used for the parser. Perhaps change all prefix to use \ (e.g. "a\") since \ is less commonly used than /.

**Comment by rockman007372** [comment]
I agree with @junianob, we can add this design flaw in the DG.
