### ISSUE TITLE
[GUI] Make the tags look better

### ISSUE THREAD

**Issue by rockman007372** [AY2223S2-CS2103T-W11-3/tp#130]
Currently tags look very buggy:

![image](https://user-images.githubusercontent.com/80334013/226010176-2f2a05a4-db9e-42cc-9bef-9634c58ce418.png)

**Comment by junianob** [comment]
#146 kinda done? Let me know if there's anything that needs improving

**Comment by rockman007372** [comment]
It looks very neat, thank you @junianob
