### ISSUE TITLE
[Review] To remove MarkCorrect and MarkWrong, replace with tagging Easy, Medium, Hard

### ISSUE THREAD

**Issue by unfazing** [AY2223S2-CS2103T-W11-3/tp#189]

**Comment by ruiyigan** [comment]
Do you want me to do it together with the Tag? If someone tags a card, does this move to the next card or they still have to click next.

**Comment by unfazing** [comment]
i think Nathan wants to do this issue. the bahviour is user needs to press next.

**Comment by rockman007372** [comment]
@ruiyigan I will wait until you finish with the tag issue!
