### ISSUE TITLE
[PE-D][Tester B] Help window does not show up after being minimised

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103T-W11-3/tp#279]
### Steps to reproduce

1. Open help via any means. (I used the `help` command)
2. Minimise help by clicking the minimise button

![image.png](https://raw.githubusercontent.com/daitenshionyan/ped/main/files/5b85c0cf-00fa-453a-9450-99ba2a9b2f92.png)

3. Repeat step 1. Help does not show up.

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: daitenshionyan/ped#7

**Comment by junianob** [comment]
closed with #313

**Comment by junianob** [comment]
closed with #313
