### ISSUE TITLE
[PE-D][Tester C] Slight mistake in error message for `review` command

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103T-W11-3/tp#283]
![image.png](https://raw.githubusercontent.com/jianminglok/ped/main/files/c881a4a2-36cd-49d0-bf64-c36ef263e40d.png)

The error message indicates that the card index provided is invalid, but the command is actually asking for a deck index instead

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: jianminglok/ped#6

**Comment by junianob** [comment]
fixed with #310
