### ISSUE TITLE
[PE-D][Tester B] Similar names allowed

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103T-W11-3/tp#286]
![image.png](https://raw.githubusercontent.com/daitenshionyan/ped/main/files/95b793d2-caae-46d9-9b58-82ad2db4998b.png)

From the image, the 3 decks have very similar name that I believe should be considered duplicates (especially number 3).

1. The default deck.
2. Deck with lower case but same characters as the first.
3. Deck with an extra space in the middle.

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: daitenshionyan/ped#10

**Comment by ruiyigan** [comment]
Discussed and concluded we allowed this as deck names may be acronyms.
