### ISSUE TITLE
[Emergency] Refractor Model class

### ISSUE THREAD

**Issue by rockman007372** [AY2223S2-CS2103T-W11-3/tp#52]
- [x] Refractor Person class to PowerCard class
- [x] Refractor UniquePersonList to UniqueCardList
- [x] Refractor Addressbook to Deck
- [x] Refractor ReadOnlyAddressBook to ReadOnlyDeck
- [x] Refractor Model's methods based on DeckModel (**Keep the class name Model**, but refractor all the methods)
- [x] Refractor ModelManager's methods based on DeckModelManager (**Keep the class name ModelManager**, but refractor all the methods)

**Comment by unfazing** [comment]
Make sure the UI and build is working before every commit
- run the build and fix any issues (e.g. checkstyle violations)
- run the main.main() and see GUI appear without any javafx error logged
