### ISSUE TITLE
Add a skeletal PPP

### ISSUE THREAD

**Issue by unfazing** [AY2223S2-CS2103T-W11-3/tp#6]
Just the headings are enough. You can write to be added soon as placeholders for content.
PDF conversion not required.

Suggested Headings:
1. Overview: A short overview of your product to provide some context to the reader. The opening 1-2 sentences may be reused by all team members. If your product overview extends beyond 1-2 sentences, the remainder should be written by yourself.
2. Summary of Contributions --Suggested items to include:
  - Code contributed: Give a link to your code on tP Code Dashboard. The link is available in the Project List Page -- linked to the icon under your profile picture.
  - Enhancements implemented: A summary of the enhancements you implemented.
  - Contributions to the UG: Which sections did you contribute to the UG?
  - Contributions to the DG: Which sections did you contribute to the DG? Which UML diagrams did you add/updated?
  - Contributions to team-based tasks
  - Review/mentoring contributions: Links to PRs reviewed, instances of helping team members in other ways.
  - Contributions beyond the project team:
    - Evidence of helping others e.g. responses you posted in our forum, bugs you reported in other team's products,
    - Evidence of technical leadership e.g. sharing useful information in the forum

**Comment by ruiyigan** [comment]
I closed this since this is individual work right?
